name: Vercel Deploy

on:
  push:
    branches:
      - main  # Ajuste conforme necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install  # Ou npm install se estiver usando npm

      - name: Construir
        run: npm run build  # Ou npm run build se estiver usando npm

      - name: Deploy para Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }}
