name: Vercel Deploy

on:
  push:
    branches:
      - main  # Ajuste conforme necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Vercel CLI
        run: npm install --global vercel@latest  # Ou npm install se estiver usando npm

      - name: Pull to vercel
        run: vercel pull --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build para Vercel
        run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

      - name: Deploy para Vercel
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Start server
        run: npm run start:prod

      
